[project]
name = "telegram-fact-checker"
version = "1.0.0"
description = "Telegram fact-checking bot using Perplexity AI"
requires-python = ">=3.11"
dependencies = [
    "aiogram==3.15.0",
    "openai==1.58.1",
    "asyncpg==0.30.0",
    "pydantic==2.9.2"
]
